- hosts: localhost
  tasks:
    - name: Slurp kubeadm generated kubeconfig
      slurp:
        src: /etc/kubernetes/admin.conf
      delegate_to: "{{ groups['control_plane'][0] }}"
      register: kubeconfig
      become: true
      no_log: false

    # - debug:
        # var:  hostvars[groups['control_plane'][0]]

    - name: Create .kube folder if it doesn't exist
      file:
        path: ~/.kube
        state: directory
        mode: "0755"

    - name: write kubeconfig locally
      copy:
        content: "{{ kubeconfig['content'] | b64decode | replace('127.0.0.1', hostvars[groups['control_plane'][0]].ansible_host) }}"
        dest: ~/.kube/config
      no_log: false