- hosts: inkus_cluster
  become: yes
  tasks:
    - name: ensure open-iscsi is present for longhorn to work
      apt:
        name: open-iscsi
        state: present
        # update-cache: yes

- hosts: localhost

  vars:
    kubeconfig_path: "~/.kube/inkus.kubeconfig"

  tasks:

########### LONGHORN

    - name: add longhorn chart repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"
        force_update: true
    
    - name: install longhorn chart
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig_path }}"
        name: longhorn
        chart_ref: longhorn/longhorn
        chart_version: 1.6.0
        release_namespace: longhorn-system
        create_namespace: true
        values: {}