
- hosts: localhost

  vars:
    kubeconfig_path: "~/.kube/kluster.kubeconfig"

  tasks:
    
########### KUBE PROMETHEUS STACK

    - name: add kube prometheus chart repo
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"
        force_update: true

    - name: install kube prometheus chart
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig_path }}"
        name: kube-prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        chart_version: 57.0.3
        release_namespace: kube-prometheus
        create_namespace: true
        values:
          ingress:
            enabled: true
            hosts:
              - prometheus.kluster.dopl.uk
            # tls:
            #   - secretName: prometheus-tls-secret
            #     hosts: 
            #       - prometheus.kluster.dopl.uk
            annotations:
              cert-manager.io/cluster-issuer: selfsigned
              kubernetes.io/ingress.class: nginx
          grafana:
            ingress:
              enabled: true
              hosts:
                - grafana.kluster.dopl.uk
              tls:
                - secretName: grafana-tls-secret 
                  hosts: 
                    - grafana.kluster.dopl.uk
              annotations:
                cert-manager.io/cluster-issuer: selfsigned
                kubernetes.io/ingress.class: nginx
