all:
  children:
    control_plane:
      hosts:
        kluster-cp0:
          ansible_host: 192.168.1.3
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
    kluster_cluster:
      hosts:
        kluster-cp0: {}
        kluster-worker0:
          ansible_host: 192.168.1.129
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
        kluster-worker1:
          ansible_host: 192.168.1.184
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
        kluster-worker2:
          ansible_host: 192.168.1.112
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
        kluster-worker3:
          ansible_host: 192.168.1.85
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
        kluster-worker4:
          ansible_host: 192.168.1.199
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
    ungrouped:
      hosts:
        backup-s3:
          ansible_host: 192.168.1.167
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
    workers:
      hosts:
        kluster-worker0: {}
        kluster-worker1: {}
        kluster-worker2: {}
        kluster-worker3: {}
        kluster-worker4: {}