all:
  children:
    control_plane:
      hosts:
        inkus-cp0: {}
    inkus_cluster:
      hosts:
        inkus-cp0:
          ansible_host: 192.168.1.3
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
        inkus-worker0:
          ansible_host: 192.168.1.129
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
        inkus-worker1:
          ansible_host: 192.168.1.184
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
        inkus-worker2:
          ansible_host: 192.168.1.112
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
        inkus-worker3:
          ansible_host: 192.168.1.85
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
        inkus-worker4:
          ansible_host: 192.168.1.199
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
        inkus-worker5:
          ansible_host: 192.168.1.199
          ansible_port: '22'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/id_k8s_incus
          ansible_user: kadmin
    workers:
      hosts:
        inkus-worker0: {}
        inkus-worker1: {}
        inkus-worker2: {}
        inkus-worker3: {}
        inkus-worker4: {}
        inkus-worker5: {}