# Pour s'y retrouver un peu de doc
# WOW merci : https://blog.zwindler.fr/2023/12/17/kubeadmcfg-introduction-api-kubeadm/
# https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-ClusterConfiguration
#

apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration

---

apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "1.29.2" # Replace with your desired version
# controlPlaneEndpoint: ""

---

apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration